### ISSUE TITLE
Mysql 연결 하기

### ISSUE THREAD

**Issue by yooonwodyd** [haedal-health/haedal-health#14]
- [ ] application.properties ->  application.yml로 바꾸기
- [ ] 테스트해보기

**Comment by oyoungsun** [comment]
아직 localDB라 merge하면 꼬일 수 있는 가능 성을 염두해 local로 실행만 해보고 git에는 코드를 업로드 하지 않기로 함. 나중에 서버를 올리게 되면 수정할 예정.
